/* OpmlExportSettings.cs
 * ==========
 * 
 * FeedDotNet (http://www.codeplex.com/FeedDotNet/)
 * Copyright © 2007 Konstantin Gonikman. All Rights Reserved.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining 
 * a copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
*/

using System;
using System.Collections.Generic;
using System.Text;
using FeedDotNet.Common;

namespace FeedDotNet
{
    public class OpmlExportSettings
    {
        private bool useFirstCategoryAsRoot = true;
        private OpmlVersion opmlVersion = OpmlVersion.V10;
        private string comment = " OPML generated by FeedDotNet (http://www.codeplex.com/FeedDotNet/) on " + DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString() + " ";
        private string title = "OPML Export";
        private string ownerName = String.Empty;

        /// <summary>
        /// Set to False, if the first category should be ignored (used as root category). Default is True.
        /// </summary>
        public bool UseFirstCategoryAsRoot
        {
            get { return useFirstCategoryAsRoot; }
            set { useFirstCategoryAsRoot = value; }
        }

        /// <summary>
        /// OPML version of the output file. Default is 1.0.
        /// </summary>
        public OpmlVersion OpmlVersion
        {
            get { return opmlVersion; }
            set { opmlVersion = value; }
        }

        /// <summary>
        /// Comment string inserted on the top of the OPML file.
        /// </summary>
        public string Comment
        {
            get { return comment; }
            set { comment = value; }
        }

        /// <summary>
        /// Title of the OPML file (Not the file name).
        /// </summary>
        public string Title
        {
            get { return title; }
            set { title = value; }
        }

        /// <summary>
        /// The person who created the OPML file.
        /// </summary>
        public string OwnerName
        {
            get { return ownerName; }
            set { ownerName = value; }
        }

        public OpmlExportSettings()
        {
        }
    }
}
